# find out int type of data from given arguments 
(1,1.5,[10,20,'Hello'],100,True)

In [2]:
l = [1,1.5,[10,20,'Hello'],100,True]

In [3]:
l

[1, 1.5, [10, 20, 'Hello'], 100, True]

In [4]:
for i in l:
    print(i)

1
1.5
[10, 20, 'Hello']
100
True

In [5]:
for i in l:
    print(i, type(i))

1 <class 'int'>
1.5 <class 'float'>
[10, 20, 'Hello'] <class 'list'>
100 <class 'int'>
True <class 'bool'>

In [7]:
l

[1, 1.5, [10, 20, 'Hello'], 100, True]

In [6]:
for i in l:
    if type(i) == int:
        print(i)
    elif type(i) == list:
        for obj in i:
            if type(obj) == int:
                print(obj)

1
10
20
100

In [9]:
print(10)

10

In [10]:
def test(num):
    for i in range(num):
        print(i)

In [11]:
test(5)

0
1
2
3
4

In [12]:
def test2(num):
    for i in range(num):
        return i

In [13]:
test2(5)

0

# Kwargs

In [14]:
def test3(**kwargs):
    return kwargs

In [20]:
test3(a = 2, b= 5)

{'a': 2, 'b': 5}

In [24]:
# Fun data entry
def test4(**kwargs):
    return kwargs.keys(), kwargs.values()

In [25]:
test4(Name= 'Python', Age = 30, Number = 39287347984)

(dict_keys(['Name', 'Age', 'Number']),
 dict_values(['Python', 30, 39287347984]))

In [32]:
d = {'a':[1,2], 'b':[2,3], 'c':[3,4]}

In [33]:
import pandas as pd
pd.DataFrame(d)

   a  b  c
0  1  2  3
1  2  3  4

In [34]:
import pandas as pd
def test4(**kwargs):
    result = pd.DataFrame(kwargs)
    return result

In [35]:
test4(names=['a','b','c'], roll_no=[10,20,30])

  names  roll_no
0     a       10
1     b       20
2     c       30

In [36]:
# mix args and kwargs

In [37]:
def test5(a,b,*args,**kwargs):
    return a , b, args, kwargs

In [41]:
test5(9, True, 10, 1.5, 'Python', 10,20,30, c=5, z=10, roll=180)

(9, True, (10, 1.5, 'Python', 10, 20, 30), {'c': 5, 'z': 10, 'roll': 180})

In [47]:
def test7():
    print('hello')

In [48]:
test7()

hello

In [49]:
def test8():
    print('Hello & hi')
        test8()

In [51]:
test8()

Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi
Hello & hi

RecursionError: maximum recursion depth exceeded while calling a Python object

In [53]:
def flower():
    print('*#*' * 10)

In [54]:
def test9():
    print('This is my house')
    flower()

In [55]:
test9()

This is my house
*#**#**#**#**#**#**#**#**#**#*

In [57]:
def test10():
    print('This is my house')
    for i in range(10):
        print(flower())

In [58]:
test10()

This is my house
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None
*#**#**#**#**#**#**#**#**#**#*
None

In [61]:
print(type(5))

<class 'int'>

In [62]:
type(5)

int

# Lambda Function

In [63]:
f = lambda a:a+5

In [64]:
f(10)

15

In [65]:
s = lambda a: a*a

In [66]:
s(2)

4

In [67]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [68]:
[i*i for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
for i in range(1,11):
    if i % 2 == 0:
        print(i)

In [69]:
[i for i in range(1,11) if i % 2 == 0]

[2, 4, 6, 8, 10]

In [ ]:
#